### PR TITLE
Remove the Acknowledgement section from the handbook

### PR DESCRIPTION
**Pull request by sayanchowdhury**
Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>

### CODE REVIEW

**Comment by ananyo2012** [comment]
@sayanchowdhury I would like to showcase all the contributors using @all-contributors-bot

**Comment by sayanchowdhury** [comment]
I feel README.md is not the right place for the contributors, as it fills the README.md with a lot of data which could be present in some other place.

Also, for the size of the projects, I would say https://github.com/pythonindia/pyconindia-handbook/graphs/contributors suffice the requirement.

**Comment by palnabarun** [comment]
IMHO, there is no logic into listing contributors in the project README. GitHub repository [contributors page](https://github.com/pythonindia/pyconindia-handbook/graphs/contributors) lists the same.

Learning by examples, I don't see many (if not any) insanely popular projects listing contributors in README.

---
Apart from that, if we start keeping a list of contributors to PyCon India since the start, we might as well create a "Thank You!" page somewhere and list _**all**_ the contributors there. By all, I mean people who have not contributed to code/GitHub too like the day of event volunteers, marketing, design, social media, and any person involved with the events. There is no merit in highlighting the contributions of some and ignoring the contributions of others.

**Comment by palnabarun** [comment]
@sayanchowdhury Do we need a lazy consensus on this?

**Comment by sayanchowdhury** [comment]
Given the PR has been open for some time and we haven't hit received any comments, we can go with a lazy consensus.

**Comment by palnabarun** [comment]
@sayanchowdhury -- merge this maybe now?

**Pull request merged**
