### PR TITLE
Things to do added to the index page

### PR DESCRIPTION
**Pull request by satyaakam**

### CODE REVIEW

**Comment by theskumar** [comment]
@satyaakam this list is great! How can we get is merged to master?

**Comment by satyaakam** [comment]
Hmm IDK , I recall creating a PR , but nobody merged it May be u can ask or fork to create a new one.

**Comment by theskumar** [comment]
@satyaakam thanks. Forking won't be a good idea. Based on commit history, i'm pinging @konarkmodi, @anandology for consideration.

**Comment by kracekumar** [comment]
@satyaakam Can you rebase ? Post that I can merge.

**Comment by satyaakam** [comment]
rebased the PR

**Pull request merged**
