### PR TITLE
Talk selection

### LINKED ISSUE #6: Talk Coordination
Write about Talk Coordination guidelines.

### PR DESCRIPTION
**Pull request by kracekumar**
- Add talk selection guidelines.
- PR is sent on behalf of @vanishan.
- Fix #6.

### CODE REVIEW

**Comment by kracekumar** [comment]
@kirang89 Please review.

**Comment by kirang89** [comment]
Looks good Krace. Could you kindly fix the conflict and recommit ? After that, I'll be more than happy to merge.

**Comment by kracekumar** [comment]
@kirang89 : Fixed conflicts.

**Comment by kirang89** [comment]
:+1:

**Pull request merged**
